export const STORAGE_KEY = "nexgensis_v1_books";
export const DELAY_MS = 300;

export const GENRES = [
    "Fiction",
    "Non-Fiction",
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Romance",
    "Biography",
    "History",
    "Science",
    "Self-Help",
    "Horror",
    "Classic",
    "Poetry",
    "Graphic Novel",
    "Other",
];

export const SORT_OPTIONS = [
    { value: "title", label: "Title A-Z" },
    { value: "author", label: "Author A-Z" },
    { value: "year_desc", label: "Newest First" },
    { value: "year_asc", label: "Oldest First" },
    { value: "rating", label: "Top Rated" },
];

export const GENRE_COLORS = {
    Fiction: "#4a5e7a",
    "Science Fiction": "#3d5a6e",
    Fantasy: "#5a4a7a",
    Mystery: "#6e4a5a",
    Thriller: "#7a4a3d",
    Romance: "#7a4a6e",
    Biography: "#4a7a5a",
    History: "#6e5a3d",
    Horror: "#7a3d3d",
    Classic: "#6e6a3d",
    "Non-Fiction": "#4a6e6a",
    "Self-Help": "#5a6e4a",
    Science: "#3d6e7a",
    Poetry: "#7a5a6e",
    "Graphic Novel": "#4a7a6e",
    Other: "#5a5a5a",
};

export const DEFAULT_BOOKS = [
    {
        id: "1",
        title: "The Memo",
        author: "Matt Haig",
        genre: "Fiction",
        year: 2020,
        rating: 4,
        cover: "https://covers.openlibrary.org/b/id/10519146-M.jpg",
    },
    {
        id: "2",
        title: "Dune",
        author: "Frank Herbert",
        genre: "Science Fiction",
        year: 1965,
        rating: 5,
        cover: "https://covers.openlibrary.org/b/id/8225312-M.jpg",
    },
    {
        id: "3",
        title: "Cracking the Coding Interview",
        author: "Gayle Laakmann McDowell",
        genre: "Non-Fiction",
        year: 2011,
        rating: 5,
        cover: "https://covers.openlibrary.org/b/id/8091016-M.jpg",
    },
    {
        id: "4",
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        genre: "Fantasy",
        year: 2007,
        rating: 5,
        cover: "https://covers.openlibrary.org/b/id/9326294-M.jpg",
    },
    {
        id: "5",
        title: "Gone Girl",
        author: "Gillian Flynn",
        genre: "Thriller",
        year: 2012,
        rating: 4,
        cover: "https://covers.openlibrary.org/b/id/7984916-M.jpg",
    },
    {
        id: "6",
        title: "1984",
        author: "George Orwell",
        genre: "Classic",
        year: 1949,
        rating: 5,
        cover: "https://covers.openlibrary.org/b/id/8575708-M.jpg",
    },
    {
        id: "7",
        title: "Atomic Habits",
        author: "James Clear",
        genre: "Self-Help",
        year: 2018,
        rating: 4,
        cover: "https://covers.openlibrary.org/b/id/10432685-M.jpg",
    },
    {
        id: "8",
        title: "The Shining",
        author: "Stephen King",
        genre: "Horror",
        year: 1977,
        rating: 4,
        cover: "https://covers.openlibrary.org/b/id/8091336-M.jpg",
    },
];
